import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { describe, it } from 'node:test'

const execFileAsync = promisify(execFile)

async function runActionInputDetector(files: string[], config = 'upstream-radar.config.json') {
  const root = await mkdtemp(join(tmpdir(), 'upstream-radar-action-input-'))
  const output = join(root, 'github-output')
  try {
    for (const file of files) await writeFile(join(root, file), '')
    const script = fileURLToPath(new URL('../../scripts/detect-action-input.mjs', import.meta.url))
    const result = await execFileAsync(process.execPath, [script], {
      cwd: root,
      env: { ...process.env, RADAR_CONFIG: config, GITHUB_OUTPUT: output },
      encoding: 'utf8',
    })
    return { stdout: result.stdout, output: await readFile(output, 'utf8') }
  } finally {
    await rm(root, { recursive: true, force: true })
  }
}

describe('reusable GitHub Action', () => {
  it('reports repository or build review failure after downstream work without hiding a successful partial observation', async () => {
    const workflow = await readFile(new URL('../../.github/workflows/upstream-observer.yml', import.meta.url), 'utf8')
    const health = workflow.slice(workflow.indexOf('\n  observer-final-health:'))
    assert.match(health, /if: always\(\)\n/)
    assert.match(workflow, /environment_review_outcome: \$\{\{ steps\.environment-recommendations\.outcome \}\}/)
    assert.match(workflow, /build_review_outcome: \$\{\{ steps\.headless-agent-plan\.outcome \}\}/)
    const command = health.split('        run: |\n')[1]!.split('\n').map(line => line.replace(/^          /, '')).join('\n')
    for (const [observer, environment, builds, shouldFail] of [
      ['0', 'success', 'success', false], ['', 'skipped', 'skipped', false],
      ['2', 'success', 'success', true], ['0', 'failure', 'success', true], ['0', 'success', 'failure', true],
    ] as const) {
      const result = execFileAsync('bash', ['-c', command], { env: { ...process.env,
        OBSERVER_EXIT: observer, ENVIRONMENT_REVIEW_OUTCOME: environment, BUILD_REVIEW_OUTCOME: builds } })
      if (shouldFail) await assert.rejects(result, (error: unknown) => (error as { code?: number }).code === 1)
      else await result
    }
  })
  it('can exercise the same scheduled adapter workflow on a validation branch without publishing project state', async () => {
    const workflow = await readFile('.github/workflows/dsh-rebuild-validation.yml', 'utf8')
    assert.ok(workflow.includes('adapter_matrix_json:'), 'validation dispatch must accept an exact planner-produced adapter matrix')
    const job = workflow.split('\n  adapter-case-validation:')[1]
    assert.ok(job)
    assert.ok(job.includes('uses: ./.github/workflows/observe-dsh-plugin-adapter.yml'))
    assert.ok(job.includes('case_json: ${{ toJSON(matrix) }}'))
    assert.doesNotMatch(job, /contents: write|secrets:|git push/)
  })

  it('routes the scheduled observer through independent adapter planning, secret-free jobs and exact result reconciliation', async () => {
    const workflow = await readFile('.github/workflows/upstream-observer.yml', 'utf8')
    assert.match(workflow, /plan-adapter-observations:[\s\S]*write-dsh-adapter-plan\.mjs/)
    const job = workflow.split('\n  adapter-observation:')[1]?.split('\n  reconcile-adapter-observations:')[0]
    assert.ok(job)
    assert.match(job, /uses: \.\/\.github\/workflows\/observe-dsh-plugin-adapter.yml/)
    assert.match(job, /case_json: \$\{\{ toJSON\(matrix\) \}\}/)
    assert.doesNotMatch(job, /secrets:|secrets\./)
    const reconcile = workflow.split('\n  reconcile-adapter-observations:')[1]?.split('\n  observer-final-health:')[0]
    assert.ok(reconcile)
    assert.match(reconcile, /merge-dsh-adapter-ledger\.mjs/)
    assert.match(reconcile, /if: always\(\)/)
    assert.match(reconcile, /git add -- adapter-ledger\.json/)
    assert.match(workflow, /name: upstream-radar-adapter-plan-\$\{\{ github.run_id \}\}/)
    assert.match(reconcile, /needs: \[plan-adapter-observations, adapter-observation, reconcile-surface-observations\]/)
    const feedSteps = workflow.split('      - name:').filter(step => step.includes('node scripts/write-dsh-directory-feed.mjs'))
    assert.equal(feedSteps.length, 4, 'every result path, including adapters, must refresh the same unified feed')
    for (const step of feedSteps) assert.match(step, /adapter-ledger\.json\s*\\\s*examples\/dsh\/install-observer\/agent-plans\.json/,
      'later native/surface refreshes must not erase adapter evidence or drop exact build decisions')
    for (const step of feedSteps) assert.match(step, /examples\/dsh\/surface-observer\/agent-plans\.json/,
      'directory coverage must bind the same Web/TUI build decisions as the scheduled surface planner')
  })

  it('offers a real rebuild batch loop that reviews observed gates, retries, and verifies unchanged reuse without giving model secrets to execution steps', async () => {
    const workflow = await readFile(fileURLToPath(new URL('../../.github/workflows/dsh-rebuild-validation.yml', import.meta.url)), 'utf8')
    assert.match(workflow, /execute_batch:/)
    const steps = workflow.split('      - name:')
    const execution = steps.filter(step => step.includes('node scripts/run-dsh-compatibility-batch.mjs'))
    assert.equal(execution.length, 6)
    for (const step of execution) {
      assert.match(step, /inputs.execute_batch/)
      assert.doesNotMatch(step, /secrets\.|ISSUE_LOCATOR_LLM/)
    }
    const first = workflow.indexOf('Run the isolated batch against current repository intent')
    const review = workflow.indexOf('Review build gates produced by this batch')
    const retry = workflow.indexOf('Retry the batch with its own exact build decisions')
    const refreshedReview = workflow.indexOf('Review refreshed host and surface build facts after retry')
    const refreshedRetry = workflow.indexOf('Retry once more with refreshed exact host facts')
    const unchanged = workflow.indexOf('Verify the completed batch does not execute unchanged cells')
    assert.ok(first > 0 && review > first && retry > review && refreshedReview > retry
      && refreshedRetry > refreshedReview && unchanged > refreshedRetry)
    assert.match(workflow.slice(review, retry), /batch-output\/compatibility-ledger.json/)
    assert.match(workflow, /summary.executed !== 0/)
    assert.match(workflow, /summary.deferredTaskKeys.length/)
    assert.match(workflow, /state.tasks.some\(task => task.status === 'running'\)/)
    assert.match(workflow, /build-approval-required/)
    assert.match(workflow, /independent adapter evidence is incomplete/)
    const directoryStep = steps.find(step => step.includes('Join this batch to the maintained catalog feed'))
    assert.ok(directoryStep, 'the real batch must exercise the same unified feed command')
    assert.match(directoryStep, /scripts\/write-dsh-directory-feed\.mjs/)
    assert.match(directoryStep, /batch-output\/adapter-ledger\.json/)
    assert.match(directoryStep, /validation-output\/build-plans\.json/)
    assert.doesNotMatch(directoryStep, /secrets\.|ISSUE_LOCATOR_LLM|git push/)
    const historical = workflow.indexOf('Collect an earlier real Context repository revision')
    const forward = workflow.indexOf('Collect the forward Context repository update')
    assert.ok(historical > unchanged && forward > historical)
    assert.match(workflow, /33fd7ae6801d892ddbee7b76a964a4b2c6ff0416/)
    assert.match(workflow, /verify-dsh-input-change\.mjs execution input-change-before/)
    assert.match(workflow, /verify-dsh-input-change\.mjs execution input-change-after/)
    assert.match(workflow, /verify-dsh-input-change\.mjs unchanged input-change-after/)
    const replaySteps = steps.filter(step => /verify-dsh-input-change\.mjs/.test(step))
    assert.equal(replaySteps.length, 6)
    for (const step of replaySteps) assert.match(step, /if: \$\{\{ inputs.execute_batch && success\(\) \}\}/,
      'a failed observation or review must stop subsequent replay execution')
  })

  it('reviews host build failures from the actual surface ledger before an isolated retry and retains the durable decisions across validation runs', async () => {
    const workflow = await readFile(fileURLToPath(new URL('../../.github/workflows/dsh-rebuild-validation.yml', import.meta.url)), 'utf8')
    const restore = await readFile(fileURLToPath(new URL('../../scripts/restore-dsh-review-checkpoint.mjs', import.meta.url)), 'utf8')
    const first = workflow.indexOf('Run the isolated batch against current repository intent')
    const review = workflow.indexOf('Review host and surface build failures produced by this batch')
    const retry = workflow.indexOf('Retry the batch with its own exact build decisions')
    assert.ok(first >= 0 && review > first && retry > review)
    const step = workflow.slice(review, retry)
    assert.match(step, /scripts\/plan-dsh-surface-agent\.mjs/)
    assert.match(step, /batch-output\/surface-ledger\.json/)
    assert.match(step, /validation-output\/surface-build-plans\.json/)
    assert.match(step, /ISSUE_LOCATOR_LLM_API_KEY/)
    assert.match(restore, /surface-build-plans\.json/)
    const execution = workflow.split('      - name:').filter(item => item.includes('node scripts/run-dsh-compatibility-batch.mjs'))
    for (const item of execution) assert.doesNotMatch(item, /ISSUE_LOCATOR_LLM|secrets\./)
  })

  it('runs Linux host rebuild boundary tests only inside a disposable restricted container', async () => {
    const workflow = await readFile(fileURLToPath(new URL('../../.github/workflows/dsh-rebuild-validation.yml', import.meta.url)), 'utf8')
    const step = workflow.split('      - name:').find(item => item.startsWith(' Verify host rebuild boundary in a disposable container'))
    assert.ok(step)
    assert.match(step, /docker build --target build/)
    assert.match(step, /docker run --rm --read-only --network none/)
    assert.match(step, /--user 10001:10001/)
    assert.match(step, /--cap-drop ALL --security-opt no-new-privileges/)
    assert.match(step, /--tmpfs \/tmp:rw,exec,nosuid,nodev,size=64m/)
    assert.match(step, /UPSTREAM_RADAR_ISOLATED_RUNNER=1/)
    assert.match(step, /dist\/test\/dsh-host-build-execution\.test\.js/)
    assert.doesNotMatch(step, /secrets\.|ISSUE_LOCATOR_LLM|--mount|--volume/)
  })

  it('carries the selected profile environment from each matrix into the image and isolated probe', async () => {
    const workflow = await readFile(fileURLToPath(new URL('../../.github/workflows/upstream-observer.yml', import.meta.url)), 'utf8')
    assert.equal(workflow.match(/profile_environment_json: \$\{\{ toJSON\(matrix\.profileEnvironment\) \}\}/g)?.length, 2)
    assert.match(workflow, /artifact_sha256: \$\{\{ matrix\.expectedArtifactSha256 \|\| '' \}\}/)
    for (const kind of ['install', 'surface']) {
      const observer = await readFile(fileURLToPath(new URL(`../../.github/workflows/observe-dsh-plugin-${kind}.yml`, import.meta.url)), 'utf8')
      assert.equal(observer.match(/^      profile_environment_json:$/gm)?.length, 2, `${kind}: manual and reusable inputs`)
      assert.match(observer, /RADAR_PROFILE_ENVIRONMENT: \$\{\{ inputs\.profile_environment_json \}\}/)
      assert.match(observer, /--build-arg PNPM_VERSION="\$RADAR_PNPM_VERSION"/)
      assert.match(observer, /--profile-environment-json "\$RADAR_PROFILE_ENVIRONMENT"/)
      assert.doesNotMatch(observer, /run:.*\$\{\{ inputs\.profile_environment_json/)
    }
  })

  it('forwards each supplemental startup configuration to the surface probe without changing default startup', async () => {
    const workflow = await readFile(fileURLToPath(new URL('../../.github/workflows/upstream-observer.yml', import.meta.url)), 'utf8')
    const observer = await readFile(fileURLToPath(new URL('../../.github/workflows/observe-dsh-plugin-surface.yml', import.meta.url)), 'utf8')
    assert.equal(workflow.match(/startup_configuration_json: \$\{\{ matrix\.startupConfiguration && toJSON\(matrix\.startupConfiguration\) \|\| '' \}\}/g)?.length, 1)
    assert.equal(observer.match(/^      startup_configuration_json:$/gm)?.length, 2, 'manual and reusable inputs')
    assert.match(observer, /RADAR_STARTUP_CONFIGURATION: \$\{\{ inputs\.startup_configuration_json \}\}/)
    assert.match(observer, /startup_args=\(\)\s+if \[\[ -n "\$RADAR_STARTUP_CONFIGURATION" \]\]; then\s+startup_args\+=\(--startup-configuration-json "\$RADAR_STARTUP_CONFIGURATION"\)/)
    assert.match(observer, /"\$\{startup_args\[@\]\}"/)
    assert.doesNotMatch(observer, /run:.*\$\{\{ inputs\.startup_configuration_json/)
  })

  it('keeps the published Action thin, pinned, and frozen', async () => {
    const actionPath = fileURLToPath(new URL('../../action.yml', import.meta.url))
    const examplePath = fileURLToPath(new URL('../../examples/github-actions/upstream-radar.yml', import.meta.url))
    const observerWorkflowPath = fileURLToPath(new URL('../../examples/github-actions/upstream-observer.yml', import.meta.url))
    const minimalObserverWorkflowPath = fileURLToPath(new URL('../../examples/github-actions/upstream-observer-minimal.yml', import.meta.url))
    const reviewWorkflowPath = fileURLToPath(new URL('../../examples/github-actions/dsh-plugin-review-minimal.yml', import.meta.url))
    const checkedInReviewWorkflowPath = fileURLToPath(new URL('../../.github/workflows/review-dsh-plugin.yml', import.meta.url))
    const checkedInObserverWorkflowPath = fileURLToPath(new URL('../../.github/workflows/upstream-observer.yml', import.meta.url))
    const observerTargetsPath = fileURLToPath(new URL('../../examples/upstream-observer/targets.yml', import.meta.url))
    const detectorPath = fileURLToPath(new URL('../../scripts/detect-action-input.mjs', import.meta.url))
    const packagePath = fileURLToPath(new URL('../../package.json', import.meta.url))
    const installObserverDockerfilePath = fileURLToPath(new URL('../../docker/dsh-install-observer.Dockerfile', import.meta.url))
    const surfaceObserverDockerfilePath = fileURLToPath(new URL('../../docker/dsh-surface-observer.Dockerfile', import.meta.url))
    const surfaceObserverWorkflowPath = fileURLToPath(new URL('../../.github/workflows/observe-dsh-plugin-surface.yml', import.meta.url))
    const surfaceTargetsPath = fileURLToPath(new URL('../../examples/dsh/surface-observer/targets.json', import.meta.url))
    const action = await readFile(actionPath, 'utf8')
    const example = await readFile(examplePath, 'utf8')
    const observerWorkflow = await readFile(observerWorkflowPath, 'utf8')
    const minimalObserverWorkflow = await readFile(minimalObserverWorkflowPath, 'utf8')
    const reviewWorkflow = await readFile(reviewWorkflowPath, 'utf8')
    const checkedInReviewWorkflow = await readFile(checkedInReviewWorkflowPath, 'utf8')
    const checkedInObserverWorkflow = await readFile(checkedInObserverWorkflowPath, 'utf8')
    const observerTargets = await readFile(observerTargetsPath, 'utf8')
    const detector = await readFile(detectorPath, 'utf8')
    const installObserverDockerfile = await readFile(installObserverDockerfilePath, 'utf8')
    const surfaceObserverDockerfile = await readFile(surfaceObserverDockerfilePath, 'utf8')
    const surfaceObserverWorkflow = await readFile(surfaceObserverWorkflowPath, 'utf8')
    const surfaceTargets = await readFile(surfaceTargetsPath, 'utf8')
    const packageJson = JSON.parse(await readFile(packagePath, 'utf8')) as { version?: unknown }

    assert.equal(typeof packageJson.version, 'string')
    assert.match(action, /pnpm-lock:/)
    assert.match(action, /npm-lock:/)
    assert.match(action, /root:/)
    assert.match(action, /Build Radar config from pnpm lockfile/)
    assert.match(action, /init --pnpm-lock "\$RADAR_LOCKFILE"/)
    assert.match(action, /init --npm-lock "\$RADAR_LOCKFILE"/)
    assert.match(action, /--root "\$RADAR_ROOT"/)
    assert.match(action, /root_args=\(\)/)
    assert.doesNotMatch(action, /root is required when pnpm-lock is set/)
    assert.match(action, /id: detect-project-input/)
    assert.match(detector, /kind = 'config'/)
    assert.match(detector, /kind = 'pnpm'/)
    assert.match(detector, /kind = 'npm'/)
    assert.match(detector, /kind = 'ambiguous'/)
    assert.match(detector, /kind = 'missing'/)
    assert.match(action, /No reviewed Radar config or supported lockfile was found/)
    assert.match(action, /steps\.detect-project-input\.outputs\.kind/)
    assert.match(action, /if: inputs\.pnpm-lock != ''/)
    assert.match(action, /if: inputs\.npm-lock != '' \|\| \(inputs\.npm-lock == '' && inputs\.pnpm-lock == '' && steps\.detect-project-input\.outputs\.kind == 'npm'\)/)
    assert.match(action, /if: inputs\.pnpm-lock == '' && inputs\.npm-lock == ''/)
    assert.match(action, /pnpm-lock and npm-lock are mutually exclusive/)
    assert.match(action, /if: inputs\.pnpm-lock != '' \|\| inputs\.npm-lock != ''/)
    assert.match(action, /node "\$GITHUB_ACTION_PATH\/scripts\/detect-action-input\.mjs"/)
    assert.match(action, /runs:\n\s+using: composite/)
    assert.match(action, new RegExp(`default: ${String(packageJson.version).replaceAll('.', '\\.')}`))
    assert.match(action, /description: ['"]Radar state path; use :memory: for an independent CI check\.['"]/)
    assert.match(action, /description: ['"]Compatibility changes that fail the job: never, breaking, or any\.['"]/)
    assert.match(action, /uses: pnpm\/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6\.0\.10/)
    assert.match(action, /uses: actions\/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7\.0\.0/)
    assert.match(action, /RADAR_CONFIG: \$\{\{ inputs\.config \}\}/)
    assert.match(action, /RADAR_FAIL_ON: \$\{\{ inputs\.fail-on \}\}/)
    assert.match(action, /RADAR_FAIL_ON_COMPATIBILITY: \$\{\{ inputs\.fail-on-compatibility \}\}/)
    assert.match(action, /RADAR_THREAT_INTEL: \$\{\{ inputs\.threat-intel \}\}/)
    assert.match(action, /description: ['"]When true, query CISA KEV and FIRST EPSS to prioritize matched CVEs; default is false for a lean CI gate\.['"]/)
    assert.match(action, /RADAR_STATE: \$\{\{ inputs\.state \}\}/)
    assert.match(action, /RADAR_VERSION: \$\{\{ inputs\.version \}\}/)
    assert.match(action, /probe-package:/)
    assert.match(action, /probe-dsh-versions:/)
    assert.match(action, /probe-timeout:/)
    assert.match(action, /inspect-package:/)
    assert.match(action, /inspect-fail-on:/)
    assert.match(action, /id: inspect-package/)
    assert.match(action, /inspect "npm:\$RADAR_INSPECT_PACKAGE"/)
    assert.match(action, /--deep/)
    assert.match(action, /RADAR_INSPECT_FAIL_ON: \$\{\{ inputs\.inspect-fail-on \}\}/)
    assert.match(action, /value: \$\{\{ steps\.inspect-package\.outputs\.verdict \}\}/)
    assert.match(action, /id: dsh-load-matrix/)
    assert.match(action, /npm pack --ignore-scripts/)
    assert.match(action, /probe dsh-matrix/)
    assert.match(action, /value: \$\{\{ steps\.dsh-load-matrix\.outputs\.result \}\}/)
    assert.match(action, /pnpm dlx --package="upstream-radar@\$RADAR_VERSION" upstream-radar/)
    assert.match(action, /--frozen/)
    assert.match(action, /--state "\$RADAR_STATE"/)
    assert.match(action, /--fail-on "\$RADAR_FAIL_ON"/)
    assert.match(action, /--fail-on-compatibility "\$RADAR_FAIL_ON_COMPATIBILITY"/)
    assert.match(action, /threat_intel_args=\(\)/)
    assert.match(action, /threat_intel_args=\(--threat-intel\)/)
    assert.match(action, /--json/)
    assert.match(action, /GITHUB_STEP_SUMMARY/)
    assert.match(action, /scripts\/action-summary\.mjs/)
    assert.match(action, /PIPESTATUS\[0\]/)
    assert.doesNotMatch(action, /pnpm install|npm install/)
    assert.match(example, /auto-detects one pnpm-lock\.yaml or package-lock\.json/)
    assert.doesNotMatch(example, /^\s+config:\s/m)
    assert.match(example, /fail-on-compatibility: breaking/)
    assert.match(observerWorkflow, /schedule:/)
    assert.match(observerWorkflow, /contents: write/)
    assert.match(observerWorkflow, /observe \\\n\s+examples\/upstream-observer\/targets\.yml/)
    assert.match(observerWorkflow, /cp examples\/dsh\/first-batch\/reverse-dependency-index\.json/)
    assert.match(observerWorkflow, /--reverse-index "\$RUNNER_TEMP\/reverse-dependency-index\.json"/)
    assert.match(observerWorkflow, /observations\.json/)
    assert.match(observerWorkflow, /--retry-pending/)
    assert.match(observerWorkflow, /git diff --cached --quiet/)
    assert.match(observerWorkflow, /secrets\.ISSUE_LOCATOR_LLM_BASE_URL/)
    assert.match(observerWorkflow, /secrets\.ISSUE_LOCATOR_LLM_API_KEY/)
    assert.match(observerWorkflow, /secrets\.ISSUE_LOCATOR_LLM_MODEL/)
    assert.match(observerWorkflow, /--llm-env-file "\$llm_env_file"/)
    assert.match(observerWorkflow, /static observation will still run/)
    assert.match(minimalObserverWorkflow, new RegExp(`npx --yes upstream-radar@${String(packageJson.version).replaceAll('.', '\\.')}`))
    assert.match(minimalObserverWorkflow, /workflow_dispatch:/)
    assert.match(minimalObserverWorkflow, /schedule:/)
    assert.match(minimalObserverWorkflow, /contents: write/)
    assert.match(minimalObserverWorkflow, /observe "\$repository"/)
    assert.match(minimalObserverWorkflow, /--retry-pending/)
    assert.match(minimalObserverWorkflow, /observations\.json/)
    assert.doesNotMatch(minimalObserverWorkflow, /pnpm install|pnpm build/)
    assert.match(reviewWorkflow, /finding\.remediation/)
    assert.match(checkedInReviewWorkflow, /finding\.remediation/)
    assert.match(checkedInObserverWorkflow, /agent-retry/)
    assert.match(checkedInObserverWorkflow, /--retry-pending-only/)
    assert.match(checkedInObserverWorkflow, /plan-surface-observations:/)
    assert.match(checkedInObserverWorkflow, /surface-observation:/)
    assert.match(checkedInObserverWorkflow, /surface-observation:\n\s+needs: plan-surface-observations\n\s+#.*\n\s+#.*\n\s+if: always\(\) && needs\.plan-surface-observations\.result == 'success'/)
    assert.match(checkedInObserverWorkflow, /reconcile-surface-observations:/)
    assert.match(checkedInObserverWorkflow, /scripts\/write-dsh-surface-plan\.mjs/)
    assert.match(checkedInObserverWorkflow, /scripts\/plan-dsh-surface-agent\.mjs/)
    assert.match(checkedInObserverWorkflow, /scripts\/merge-dsh-surface-ledger\.mjs/)
    assert.match(checkedInObserverWorkflow, /write-dsh-surface-plan\.mjs[\s\S]*install-observer\/agent-plans\.json[\s\S]*surface-observer\/agent-plans\.json/)
    assert.match(surfaceTargets, /"autoDiscover"\s*:\s*\{\s*"webClientGaps"\s*:\s*true/)
    assert.match(checkedInObserverWorkflow, /accept_bounded_unknown: true/)
    assert.match(surfaceObserverWorkflow, /permissions:\n\s+contents: read/)
    assert.match(surfaceObserverWorkflow, /--read-only/)
    assert.match(surfaceObserverWorkflow, /--cap-drop ALL/)
    assert.match(surfaceObserverWorkflow, /--security-opt no-new-privileges=true/)
    assert.match(surfaceObserverWorkflow, /UPSTREAM_RADAR_ISOLATED_RUNNER=1/)
    assert.doesNotMatch(surfaceObserverWorkflow, /\$\{\{\s*secrets\./)
    assert.match(surfaceObserverDockerfile, /chromium/)
    assert.match(surfaceObserverDockerfile, /playwright-core@1\.62\.0/)
    assert.match(surfaceObserverDockerfile, /node-pty@1\.1\.0/)
    for (const dockerfile of [installObserverDockerfile, surfaceObserverDockerfile]) {
      assert.match(dockerfile, /FROM node:24-bookworm-slim AS build/)
      assert.match(dockerfile, /FROM node:\$\{NODE_MAJOR\}-bookworm-slim AS runtime/)
    }
    const observationPersistStep = checkedInObserverWorkflow.indexOf('name: Persist observation and Agent planning state')
    const environmentRecommendationStep = checkedInObserverWorkflow.indexOf('name: Infer repository-recommended Node and execution profiles')
    const installPlanStep = checkedInObserverWorkflow.indexOf('name: Reconcile the current DSH compatibility matrix')
    const initialCheckoutStep = checkedInObserverWorkflow.slice(
      checkedInObserverWorkflow.indexOf('name: Check out the observer and its targets'),
      checkedInObserverWorkflow.indexOf('name: Set up pnpm'),
    )
    const installObservationJob = checkedInObserverWorkflow.indexOf('\n  install-observation:')
    const observerHealthJob = checkedInObserverWorkflow.indexOf('\n  observer-final-health:')
    const reconcileStep = checkedInObserverWorkflow.indexOf('name: Reconcile dynamic evidence into the compatibility ledger')
    const publishStep = checkedInObserverWorkflow.indexOf('name: Publish directory-consumable compatibility evidence')
    const persistStep = checkedInObserverWorkflow.indexOf('name: Persist compatibility evidence')
    const incompleteGate = checkedInObserverWorkflow.indexOf('name: Fail after persisting incomplete reconciliation')
    assert.ok(reconcileStep >= 0)
    assert.ok(observationPersistStep >= 0)
    assert.ok(environmentRecommendationStep >= 0)
    assert.ok(environmentRecommendationStep < installPlanStep)
    assert.ok(installPlanStep < observationPersistStep)
    assert.match(initialCheckoutStep, /ref: \$\{\{ github\.event\.repository\.default_branch \}\}/)
    assert.ok(installObservationJob > observationPersistStep)
    assert.ok(observerHealthJob > incompleteGate)
    assert.ok(publishStep > reconcileStep)
    assert.ok(persistStep > publishStep)
    assert.ok(incompleteGate > persistStep)
    assert.match(checkedInObserverWorkflow.slice(reconcileStep, publishStep), /continue-on-error: true/)
    const observeStep = checkedInObserverWorkflow.slice(
      checkedInObserverWorkflow.indexOf('name: Observe upstream changes'),
      checkedInObserverWorkflow.indexOf('name: Reuse current evidence for the headless Agent loop'),
    )
    assert.match(observeStep, /continue-on-error: true/)
    assert.match(checkedInObserverWorkflow.slice(observerHealthJob), /needs\.observe\.outputs\.observer_exit/)
    assert.match(checkedInObserverWorkflow.slice(observerHealthJob), /exit 1/)
    const observationPersistence = checkedInObserverWorkflow.slice(observationPersistStep, installObservationJob)
    assert.match(observationPersistence, /git diff --quiet -- \\\n\s+observations\.json \\\n\s+examples\/dsh\/environment-observer\/recommendations\.json/)
    assert.match(observationPersistence, /node scripts\/write-dsh-directory-feed\.mjs/)
    assert.match(observationPersistence, /feeds\/dsh-plugin-compatibility\.json/)
    assert.match(observationPersistence, /feeds\/dsh-plugin-compatibility\.md/)
    assert.match(observationPersistence, /environment-observer\/recommendations\.json/)
    assert.match(observationPersistence, /environment-observer\/recommendations\.md/)
    assert.match(observationPersistence, /if \[\[ -f examples\/dsh\/environment-observer\/recommendations\.json\.evidence\.json \]\]; then\s+git add -- examples\/dsh\/environment-observer\/recommendations\.json\.evidence\.json/)
    assert.ok(
      observationPersistence.indexOf('node scripts/write-dsh-directory-feed.mjs')
        < observationPersistence.indexOf('git add --'),
    )
    assert.match(checkedInObserverWorkflow.slice(incompleteGate), /if: always\(\) && steps\.ledger\.outcome == 'failure'/)
    assert.match(checkedInObserverWorkflow.slice(incompleteGate), /RADAR_MISSING: \$\{\{ steps\.ledger\.outputs\.missing \}\}/)
    assert.match(checkedInObserverWorkflow.slice(publishStep, persistStep), /feeds\/dsh-plugin-compatibility\.md \\\n\s+observations\.json/)
    const surfaceMergeStep = checkedInObserverWorkflow.indexOf('name: Reconcile plane-specific evidence into the surface ledger')
    const surfaceFeedStep = checkedInObserverWorkflow.indexOf('name: Publish execution-plane evidence to the directory feed')
    const surfacePersistStep = checkedInObserverWorkflow.indexOf('name: Persist execution-plane evidence')
    assert.ok(surfaceMergeStep >= 0)
    assert.ok(surfaceFeedStep > surfaceMergeStep)
    assert.ok(surfacePersistStep > surfaceFeedStep)
    assert.match(checkedInObserverWorkflow.slice(surfaceFeedStep, surfacePersistStep), /write-dsh-directory-feed\.mjs/)
    assert.match(checkedInObserverWorkflow.slice(surfaceFeedStep, surfacePersistStep), /surface-ledger\.json/)
    assert.match(checkedInObserverWorkflow.slice(surfacePersistStep), /git add --[\s\S]*feeds\/dsh-plugin-compatibility\.json[\s\S]*feeds\/dsh-plugin-compatibility\.md/)
    const surfacePlanJob = checkedInObserverWorkflow.slice(
      checkedInObserverWorkflow.indexOf('\n  plan-surface-observations:'),
      checkedInObserverWorkflow.indexOf('\n  surface-observation:'),
    )
    assert.match(surfacePlanJob, /permissions:\n\s+contents: write/)
    assert.match(surfacePlanJob, /secrets\.ISSUE_LOCATOR_LLM_BASE_URL/)
    assert.match(surfacePlanJob, /secrets\.ISSUE_LOCATOR_LLM_API_KEY/)
    assert.match(surfacePlanJob, /secrets\.ISSUE_LOCATOR_LLM_MODEL/)
    assert.match(surfacePlanJob, /environment-observer\/recommendations\.json/)
    assert.match(surfacePlanJob, /git add --[\s\S]*surface-observer\/agent-plans\.json[\s\S]*surface-observer\/agent-plans\.md/)
    assert.match(installObserverDockerfile, /until corepack prepare pnpm@11\.3\.0 --activate/)
    assert.match(installObserverDockerfile, /if \[ "\$attempt" -ge 3 \]; then exit 1; fi/)
    assert.match(observerTargets, /observer-targets\/v1alpha1/)
    assert.match(observerTargets, /ecosystem: dsh/)
  })

  it('executes the same zero-config detector used by the Action', async () => {
    const configured = await runActionInputDetector(['upstream-radar.config.json', 'pnpm-lock.yaml'])
    assert.match(configured.stdout, /^kind=config\n$/)
    assert.equal(configured.output, 'kind=config\n')

    const pnpm = await runActionInputDetector(['pnpm-lock.yaml'])
    assert.match(pnpm.stdout, /^kind=pnpm\npath=pnpm-lock\.yaml\n$/)
    assert.equal(pnpm.output, 'kind=pnpm\npath=pnpm-lock.yaml\n')

    const npm = await runActionInputDetector(['package-lock.json'])
    assert.match(npm.stdout, /^kind=npm\npath=package-lock\.json\n$/)
    assert.equal(npm.output, 'kind=npm\npath=package-lock.json\n')

    const ambiguous = await runActionInputDetector(['pnpm-lock.yaml', 'package-lock.json'])
    assert.match(ambiguous.stdout, /^kind=ambiguous\n$/)
    assert.equal(ambiguous.output, 'kind=ambiguous\n')

    const missing = await runActionInputDetector([])
    assert.match(missing.stdout, /^kind=missing\n$/)
    assert.equal(missing.output, 'kind=missing\n')
  })
})
