import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { describe, it } from 'node:test'

describe('reusable GitHub Action', () => {
  it('keeps the published Action thin, pinned, and frozen', async () => {
    const actionPath = fileURLToPath(new URL('../../action.yml', import.meta.url))
    const packagePath = fileURLToPath(new URL('../../package.json', import.meta.url))
    const action = await readFile(actionPath, 'utf8')
    const packageJson = JSON.parse(await readFile(packagePath, 'utf8')) as { version?: unknown }

    assert.equal(typeof packageJson.version, 'string')
    assert.match(action, /pnpm-lock:/)
    assert.match(action, /npm-lock:/)
    assert.match(action, /root:/)
    assert.match(action, /Build Radar config from pnpm lockfile/)
    assert.match(action, /init --pnpm-lock "\$RADAR_LOCKFILE"/)
    assert.match(action, /init --npm-lock "\$RADAR_LOCKFILE"/)
    assert.match(action, /--root "\$RADAR_ROOT"/)
    assert.match(action, /root_args=\(\)/)
    assert.doesNotMatch(action, /root is required when pnpm-lock is set/)
    assert.match(action, /if: inputs\.pnpm-lock != ''/)
    assert.match(action, /if: inputs\.npm-lock != '' && inputs\.pnpm-lock == ''/)
    assert.match(action, /if: inputs\.pnpm-lock == '' && inputs\.npm-lock == ''/)
    assert.match(action, /pnpm-lock and npm-lock are mutually exclusive/)
    assert.match(action, /if: inputs\.pnpm-lock != '' \|\| inputs\.npm-lock != ''/)
    assert.match(action, /runs:\n\s+using: composite/)
    assert.match(action, new RegExp(`default: ${String(packageJson.version).replaceAll('.', '\\.')}`))
    assert.match(action, /description: ['"]Radar state path; use :memory: for an independent CI check\.['"]/)
    assert.match(action, /description: ['"]Compatibility changes that fail the job: never, breaking, or any\.['"]/)
    assert.match(action, /uses: pnpm\/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6\.0\.10/)
    assert.match(action, /uses: actions\/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7\.0\.0/)
    assert.match(action, /RADAR_CONFIG: \$\{\{ inputs\.config \}\}/)
    assert.match(action, /RADAR_FAIL_ON: \$\{\{ inputs\.fail-on \}\}/)
    assert.match(action, /RADAR_FAIL_ON_COMPATIBILITY: \$\{\{ inputs\.fail-on-compatibility \}\}/)
    assert.match(action, /RADAR_STATE: \$\{\{ inputs\.state \}\}/)
    assert.match(action, /RADAR_VERSION: \$\{\{ inputs\.version \}\}/)
    assert.match(action, /probe-package:/)
    assert.match(action, /probe-dsh-versions:/)
    assert.match(action, /probe-timeout:/)
    assert.match(action, /id: dsh-load-matrix/)
    assert.match(action, /npm pack --ignore-scripts/)
    assert.match(action, /probe dsh-matrix/)
    assert.match(action, /value: \$\{\{ steps\.dsh-load-matrix\.outputs\.result \}\}/)
    assert.match(action, /pnpm dlx --package="upstream-radar@\$RADAR_VERSION" upstream-radar/)
    assert.match(action, /--frozen/)
    assert.match(action, /--state "\$RADAR_STATE"/)
    assert.match(action, /--fail-on "\$RADAR_FAIL_ON"/)
    assert.match(action, /--fail-on-compatibility "\$RADAR_FAIL_ON_COMPATIBILITY"/)
    assert.match(action, /--json/)
    assert.match(action, /GITHUB_STEP_SUMMARY/)
    assert.match(action, /scripts\/action-summary\.mjs/)
    assert.match(action, /PIPESTATUS\[0\]/)
    assert.doesNotMatch(action, /pnpm install|npm install/)
  })
})
